### ISSUE TITLE
Question about USB-HID controller support

### ISSUE THREAD

**Issue by 25minutes** [revvv/RetroArchWiiRetrode#4]
I read the following from the readme "If you want to use an additional USB gamepad, please note: RetroArch Wii/Wii U only supports certain USB gamepads: VIDs/PIDs are [hardcoded] and an autoconfig file has to exist. As described in the official [commit message]."

The only USB-HID controller that I make it work in Nintendont is PS2 controller (using a USB adapter). Rumble works fine and it supports 2 PS2 controllers at the same time. I also have a third pary PS3 controller, but it doesn't work in Nintendont. So if possible, I'd like to make PS2 controller work in RetroArch. 

I'm not a progammer, and I don't fully understand this USB-HID support thing. I'd appreciare if you could give some suggestions.

1. The PS2 controller has VID=0810 & PID=0001. While joypad_connection.h contains the following. Does it mean this controller can be supported?
`#define VID_PCS           SWAP_IF_BIG(0x0810)`

2. As https://github.com/libretro/RetroArch/blob/master/input/connect/joypad_connection.h is actually from official RetroArch, is USB-HID controller support a feature available in official RetroArch-Wii build? To test this PS2 controller support, do you recommend that I try your RetroArch-1.7.8 build or the official RetroArch-Wii build?

3. When I test PS2 controller for Nintendont, there's a utility called HID_Test. Is there any utility I can leverage to generated the autoconfig file needed? I see there's https://github.com/libretro/retroarch-joypad-autoconfig/blob/master/hid/PS2-PSX_Controller_Adapter.cfg, but I doubt if it works.

**Comment by revvv** [comment]
1. PS2 is already supported by RA.
2. Try the official build. (Should work with my fork, too.)
3. Wii config differs from other platforms. Never found out why. You need to configure your controller with the RA menu, then save the autoconfig file.
